# Generated by Django 3.1.1 on 2020-09-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('in_stock_quantity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order_date', models.DateTimeField(null=True)),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='prezola.items')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
